# Orchestrator Configuration
# M2: WebSocket + LiveKit transport, VAD stub, static routing

transport:
  websocket:
    enabled: true
    host: "0.0.0.0"
    port: 8080
    max_connections: 100
    frame_queue_size: 50

  livekit:
    enabled: true  # Optional - system works without it
    url: "http://localhost:7880"
    api_key: "devkey"
    api_secret: "secret"
    room_prefix: "tts-session"

redis:
  url: "redis://localhost:6379"
  db: 0
  worker_key_prefix: "worker:"
  worker_ttl_seconds: 30
  connection_pool_size: 10

routing:
  # M2: Static routing to single mock worker
  static_worker_addr: "grpc://localhost:7001"

  # M9+: Dynamic routing settings (not used in M2)
  prefer_resident_models: true
  load_balance_strategy: "queue_depth"

vad:
  enabled: true
  aggressiveness: 2  # 0=least, 3=most aggressive
  sample_rate: 16000  # webrtcvad requirement
  frame_duration_ms: 20

# Operational settings
log_level: "INFO"
graceful_shutdown_timeout_s: 10
